"""Fresh start

Revision ID: 15c3f60fa8b1
Revises: 
Create Date: 2025-12-31 20:12:59.475124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c3f60fa8b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icone_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('ordre_affichage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    with op.batch_alter_table('specialites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialites_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_specialites_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('client', 'pro', name='user_role'), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=100), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('pros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specialite_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adresse_salon', sa.String(length=255), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('pays', sa.String(length=10), nullable=False),
    sa.Column('province', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('travail_salon', sa.Boolean(), nullable=True),
    sa.Column('travail_domicile', sa.Boolean(), nullable=True),
    sa.Column('distance_max_km', sa.Integer(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('total_appointments', sa.Integer(), nullable=True),
    sa.Column('late_cancellation_count', sa.Integer(), nullable=True),
    sa.Column('last_late_cancellation', sa.DateTime(), nullable=True),
    sa.Column('invisible_until', sa.DateTime(), nullable=True, comment="Invisible dans recherche jusqu'à cette date"),
    sa.ForeignKeyConstraint(['specialite_id'], ['specialites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('pros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pros_ville'), ['ville'], unique=False)

    op.create_table('availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('jour_semaine', sa.Integer(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('heure_debut < heure_fin', name='check_heures_coherences'),
    sa.ForeignKeyConstraint(['pro_id'], ['pros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availabilities_jour_semaine'), ['jour_semaine'], unique=False)
        batch_op.create_index(batch_op.f('ix_availabilities_pro_id'), ['pro_id'], unique=False)

    op.create_table('loyalty_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('points_total', sa.Integer(), nullable=True),
    sa.Column('late_cancellation_count', sa.Integer(), nullable=True),
    sa.Column('last_late_cancellation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pro_id'], ['pros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'pro_id', name='unique_client_pro')
    )
    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_accounts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_accounts_pro_id'), ['pro_id'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordre_affichage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pro_id'], ['pros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_pro_id'), ['pro_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=False),
    sa.Column('prix', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('disponible_salon', sa.Boolean(), nullable=True),
    sa.Column('disponible_domicile', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('ordre_affichage', sa.Integer(), nullable=True),
    sa.Column('points_fidelite', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pro_id'], ['pros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_pro_id'), ['pro_id'], unique=False)

    op.create_table('time_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raison', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('date_debut < date_fin', name='check_date_coherentes'),
    sa.ForeignKeyConstraint(['pro_id'], ['pros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_blocks_pro_id'), ['pro_id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('type_rdv', sa.Enum('Salon', 'Domicile', name='type_rdv_enum'), nullable=False),
    sa.Column('statut', sa.Enum('En attente', 'Confirmer', 'Terminer', 'Annuler', name='statut_enum'), nullable=False),
    sa.Column('notes_client', sa.Text(), nullable=True),
    sa.Column('notes_pro', sa.Text(), nullable=True),
    sa.Column('adresse_domicile', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prix_deplacement', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prix_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('is_late_cancellation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('heure_debut < heure_fin', name='check_heures_coherences_appointment'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pro_id'], ['pros.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_pro_id'), ['pro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_service_id'), ['service_id'], unique=False)

    op.create_table('loyalty_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('points_change', sa.Integer(), nullable=True),
    sa.Column('raison', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pro_id'], ['pros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_histories_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_histories_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_histories_pro_id'), ['pro_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating >=1 AND rating <=5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pro_id'], ['pros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_appointment_id'), ['appointment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reviews_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_pro_id'), ['pro_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_pro_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_client_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_appointment_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('loyalty_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_histories_pro_id'))
        batch_op.drop_index(batch_op.f('ix_loyalty_histories_client_id'))
        batch_op.drop_index(batch_op.f('ix_loyalty_histories_appointment_id'))

    op.drop_table('loyalty_histories')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_service_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_pro_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_date'))
        batch_op.drop_index(batch_op.f('ix_appointments_client_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_blocks_pro_id'))

    op.drop_table('time_blocks')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_pro_id'))

    op.drop_table('services')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_pro_id'))

    op.drop_table('portfolios')
    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_accounts_pro_id'))
        batch_op.drop_index(batch_op.f('ix_loyalty_accounts_client_id'))

    op.drop_table('loyalty_accounts')
    with op.batch_alter_table('availabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availabilities_pro_id'))
        batch_op.drop_index(batch_op.f('ix_availabilities_jour_semaine'))

    op.drop_table('availabilities')
    with op.batch_alter_table('pros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pros_ville'))

    op.drop_table('pros')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('specialites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialites_slug'))
        batch_op.drop_index(batch_op.f('ix_specialites_is_active'))

    op.drop_table('specialites')
    # ### end Alembic commands ###
